name: Deploy ke Render

on:
  push:
    branches:
      - master  # Ganti jika pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Login ke GitHub Packages
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/aplikasi-penilaian:latest .
          docker push ghcr.io/${{ github.actor }}/aplikasi-penilaian:latest

      - name: Deploy ke Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvaocqaj1k6c738va3kg?key=${{ secrets.RENDER_API_KEY }}"
